packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/google': ^2.0.25
  '@trpc/client': ^11.7.1
  '@trpc/server': 11.7.1
  '@types/node': ^22.18.13
  ai: ^5.0.83
  better-auth: ^1.3.34
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.7
  tsdown: ^0.15.12
  typescript: ^5.9.3
  zod: 4.1.12
