/**
 * Generated by orval v8.0.0-rc.1 🍺
 * Do not edit manually.
 * ResumeMatch API
 * OpenAPI spec version: 1.0.0
 */

import type { AxiosRequestConfig, AxiosResponse } from "axios";
import axios from "axios";

export type TodoDto = {
  id: number;
  title: string;
  completed: boolean;
};

export type Function = {
  [key: string]: unknown;
};

export const getResumeMatchAPI = () => {
  const appControllerGetHello = <TData = AxiosResponse<void>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.get("/", options);

  const todosControllerFindAll = <TData = AxiosResponse<TodoDto[]>>(
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.get("/todos", options);

  const todosControllerCreate = <TData = AxiosResponse<TodoDto>>(
    _function: Function,
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.post("/todos", _function, options);

  const todosControllerFindOne = <TData = AxiosResponse<TodoDto>>(
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.get(`/todos/${id}`, options);

  const todosControllerUpdate = <TData = AxiosResponse<TodoDto>>(
    id: string,
    _function: Function,
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.patch(`/todos/${id}`, _function, options);

  const todosControllerRemove = <TData = AxiosResponse<void>>(
    id: string,
    options?: AxiosRequestConfig
  ): Promise<TData> => axios.delete(`/todos/${id}`, options);

  return {
    appControllerGetHello,
    todosControllerFindAll,
    todosControllerCreate,
    todosControllerFindOne,
    todosControllerUpdate,
    todosControllerRemove,
  };
};
export type AppControllerGetHelloResult = AxiosResponse<void>;
export type TodosControllerFindAllResult = AxiosResponse<TodoDto[]>;
export type TodosControllerCreateResult = AxiosResponse<TodoDto>;
export type TodosControllerFindOneResult = AxiosResponse<TodoDto>;
export type TodosControllerUpdateResult = AxiosResponse<TodoDto>;
export type TodosControllerRemoveResult = AxiosResponse<void>;
